name: My First CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Print a welcome message
        run: echo "Hello from my first CI Pipeline!"

      - name: List files in the project
        run: ls -lR
